Add groups to env vars
xonsh/xonsh pull request #4026
Opened 2020-12-20 00:19 UTC by jnoortheen

ToDos:
- [ ] update document generated for envvars page
- [ ]

2020-12-24 00:51 UTC, jnoortheen commented
![env-vars-doc](https://user-images.githubusercontent.com/6702219/103047005-27400600-45b0-11eb-8b4d-7783dfca6c51.png)
here is a screen shot.

2021-01-03 09:39 UTC, jnoortheen commented
any stoppers on this? I want to add some more environment variables to the config to customize sqlite-history backend to speedup startup.

2021-01-04 15:44 UTC, gforsyth commented
Hey @jnoortheen -- I'll try to take a pass over this this week -- before I do, it looks like there are a bunch of empty artifacts in the env docs screenshot you posted.  Were those resolved in a later commit?

2021-01-04 15:47 UTC, jnoortheen commented
the empty part was because of the browser, because of the large size.

2021-01-04 16:30 UTC, gforsyth requested changes
Overall looks good, some nits on spelling

2021-01-04 16:30 UTC, gforsyth commented on xonsh/environ.py
> +    """``cd`` Behaviour"""
```suggestion
    """``cd`` Behavior"""
```

We use US spelling in the rest of the docs, so I'd like to keep that consistent

2021-01-04 16:30 UTC, gforsyth commented on xonsh/environ.py
> +        "Flag for directory pushing functionality. False is the normal " "behavior.",
```suggestion
        "Flag for directory pushing functionality. False is the normal behavior.",
```

2021-01-04 16:30 UTC, gforsyth commented on xonsh/environ.py
> +    """Interpreter Behaviour"""
```suggestion
    """Interpreter Behavior"""
```

2021-01-04 16:30 UTC, gforsyth commented on xonsh/environ.py
> +    """Prompt Tool Kit shell
```suggestion
    """Prompt Toolkit shell
```

2021-01-04 16:30 UTC, gforsyth commented on xonsh/environ.py
> +    """Tab-completion behaviour."""
```suggestion
    """Tab-completion behavior."""
```

2021-01-04 16:30 UTC, gforsyth commented on xonsh/environ.py
> +    """Prompt Tool Kit  auto-completion"""
```suggestion
    """Prompt Toolkit tab-completion"""
```

2021-01-04 16:31 UTC, jnoortheen commented on docs/jinja_rst_ext.py
> +        Path(cur_dir / "_build" / f"{docname}.rst.out").write_text(rendered)
that was for debugging, seems I missed it.

2021-01-04 16:36 UTC, jnoortheen commented on docs/jinja_rst_ext.py
> +            # loader=jinja2.FileSystemLoader("."),
done

2021-01-04 16:37 UTC, jnoortheen commented on docs/jinja_rst_ext.py
> +        Path(cur_dir / "_build" / f"{docname}.rst.out").write_text(rendered)
I've commented them.

2021-01-04 16:42 UTC, jnoortheen commented
I tried to publish it to github pages here https://jnoortheen.github.io/xonsh/envvars.html
the css files aren't loaded. But you can have an overview from the image and this page of what will change.

2021-01-04 17:21 UTC, merged

2021-01-04 17:21 UTC, gforsyth commented
Thanks for putting this in @jnoortheen !