Feat abbrevs callback
xonsh/xonsh pull request #4031
Opened 2020-12-25 14:37 UTC by jnoortheen

fixes #3642

2021-01-06 14:54 UTC, jnoortheen commented
@gforsyth while you are at it, these are good to go as well #4031 #4032

2021-01-06 15:36 UTC, gforsyth commented
@laloch -- do you have time to look this over?  I haven't spent much time in the `abbrevs` code

2021-01-24 08:50 UTC, jnoortheen commented
@gforsyth this doesn't change any of the existing functionality. Just adds a new feature. Please check the docstring of the module for that added functionality.

2021-01-28 17:48 UTC, gforsyth requested changes
Sorry it took me a bit to get to this @jnoortheen -- overall looks good, just two small questions

2021-01-29 14:19 UTC, jnoortheen commented on xonsh/xontribs_meta.py
> +    print("run get module")
Yes it is. I will remove.

2021-01-29 14:23 UTC, jnoortheen commented on xonsh/xontribs_meta.py
> +    from pathlib import Path
I did some testings and amalgamate doesn't do much improvement on ssd. I think, unless there is some comment on removing amalgamate altogether. The imports can be placed on the top, they don't have much import cost.

2021-01-29 17:18 UTC, gforsyth approved these changes
looks good!  thanks for putting this in!

2021-01-29 17:18 UTC, merged