Add 'dict' merging operation for the aliases class
xonsh/xonsh pull request #4037
Opened 2020-12-26 23:42 UTC by AsafFisher

This PR allows you to do the following:
```
my_aliases = {
      'ip': 'ip -c',
      'gst': 'git status'
}
aliases |= my_aliases
```

2020-12-29 20:11 UTC, AsafFisher commented
What is `lint/xonsh`?

2020-12-29 21:18 UTC, daniel-shimon commented
> What is `lint/xonsh`?

You need to add a news file for the changelog. See the contribution docs

2020-12-31 07:45 UTC, AsafFisher commented
Cool!
> > What is `lint/xonsh`?
> 
> You need to add a news file for the changelog. See the contribution docs

2020-12-31 15:49 UTC, daniel-shimon requested changes

2020-12-31 16:03 UTC, AsafFisher commented on xonsh/aliases.py
> +        return self
From [python](https://docs.python.org/3/reference/datamodel.html#object.__ior__) docs:
`These methods are called to implement the augmented arithmetic assignments (+=, -=, *=, @=, /=, //=, %=, **=, <<=, >>=, &=, ^=, |=). These methods should attempt to do the operation in-place (modifying self) and return the result (which could be, but does not have to be, self). If a specific method is not defined, the augmented assignment falls back to the normal methods.`

2020-12-31 16:04 UTC, AsafFisher commented on xonsh/aliases.py
> +            self.__setitem__(key, other[key])
`self[]`?

2020-12-31 16:06 UTC, AsafFisher commented on xonsh/aliases.py
> +            self.__setitem__(key, other[key])
In the or operator I add it the raw dict and it does not go through the `setitem` process, here we want it to go through the `setitem` process

2020-12-31 18:37 UTC, AsafFisher commented on xonsh/aliases.py
> +            self.__setitem__(key, other[key])
d boi

2020-12-31 20:45 UTC, AsafFisher commented on news/alias_merging.rst
> +* Add '``|``' and '``|=``' operations to the ``Aliases`` class.
ג

2020-12-31 23:34 UTC, daniel-shimon commented on xonsh/aliases.py
> +        return self
Shouldn't this return an Aliases object?

2021-01-01 00:56 UTC, daniel-shimon requested changes

2021-01-01 10:27 UTC, AsafFisher commented on xonsh/aliases.py
> +        return new_dict
actually its an interesting question becase `dict | aliases` Logically would return a dict while `aliases | dict` could return an `Aliases` object, but then `dict | aliases != aliases | dict  `

2021-01-01 11:21 UTC, AsafFisher commented on xonsh/aliases.py
> +        return new_dict
`__ror__`

2021-01-01 13:46 UTC, daniel-shimon approved these changes
Ready to merge! @scopatz

2021-01-04 17:44 UTC, gforsyth approved these changes
This is great!  Thanks @AsafFisher!  And I see that this is your first time contributing to `xonsh`, so welcome!

Thanks @daniel-shimon for the thorough review :+1:

2021-01-04 17:44 UTC, merged