Added ability to set XONSH_HISTORY_FILE
xonsh/xonsh pull request #4175
Opened 2021-03-14 08:12 UTC by anki-code

2021-03-15 17:06 UTC, gforsyth commented
Hey @anki-code -- I'm fine with making this configurable, but I think the default behavior, at least with the json backend, would be to continuously overwrite the history file if this were used.
Given that, we should either have some guards against that, or a warning in the env-var description

2021-03-16 05:41 UTC, anki-code commented
@gforsyth

1. I've added more logic to json backend 

2. I've tested:
```python
XONSH_HISTORY_FILE='/tmp/hist_json.json' XONSH_HISTORY_BACKEND='json' xonsh --no-rc
XONSH_HISTORY_FILE='/tmp/hist_sqlite.db' XONSH_HISTORY_BACKEND='sqlite' xonsh --no-rc
# and also https://github.com/anki-code/xontrib-history-encrypt/
```

3. All works as expected:
    * If the history file does not exist it will be created
    * After exiting or on `history flush` the history will be appended to the file (nothing is overwritten / lost)

Please merge this pr and then merge 4181

2021-03-16 15:23 UTC, anki-code commented
@gforsyth please merge.
Take a look at minor docs changes at 4169, 4172, 4174. 
Thanks!

2021-03-16 17:59 UTC, gforsyth requested changes
Thanks for putting this in @anki-code !  

I've requested a few tweaks -- and I think it would also be good to have a similar test for the sqlite history backend.

2021-03-16 17:59 UTC, gforsyth commented on tests/test_shell.py
> +def test_shell_with_json_history(xonsh_builtins, xonsh_execer, tmpdir_factory, monkeypatch):
Is `monkeypatch` being used here?

2021-03-16 17:59 UTC, gforsyth commented on xonsh/environ.py
> +        "Location of history file that could be set in RC file or it will be set by history backend.",
```suggestion
        "Location of history file set by history backend (default) or set by user in RC file.",
```

I think we also want `is_configurable=True`

2021-03-16 18:03 UTC, anki-code commented on tests/test_shell.py
> +def test_shell_with_json_history(xonsh_builtins, xonsh_execer, tmpdir_factory, monkeypatch):
nope, removed

2021-03-16 19:54 UTC, anki-code commented
@gforsyth Added tests for sqlite and for dummy in not interactive mode.

2021-03-16 21:07 UTC, gforsyth approved these changes
Woo! Thanks @anki-code !

2021-03-16 21:07 UTC, merged