Closed 4215: Added env variable to ignore ./ and ../ in filepath completion
xonsh/xonsh pull request #4241
Opened 2021-04-25 07:49 UTC by anki-code

Close #4215

2021-04-26 19:39 UTC, gforsyth requested changes
Thanks for picking this up @anki-code !  Could you add a few short tests to show that the `.` and `..` show up if the appropriate env-var is set?

2021-04-27 08:20 UTC, anki-code commented
@gforsyth tests added!

2021-04-27 13:27 UTC, gforsyth approved these changes

2021-04-27 13:28 UTC, gforsyth commented
Thanks for picking this up @anki-code !  And thanks for the initial cut @Baileymnm1999 !

2021-04-27 13:28 UTC, merged