Code cleanup
xonsh/xonsh pull request #4260
Opened 2021-05-07 07:55 UTC by jnoortheen

some random code cleanup when working with the code.

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

2021-05-08 21:51 UTC, daniel-shimon requested changes

2021-05-09 07:04 UTC, jnoortheen commented on xonsh/procs/posix.py
> -            origin = BufferedFDParallelReader(origfd, buffer=stdin)
Oh I thought it is not used and might have been leftover of some old changes. I will revert.

2021-05-09 08:52 UTC, jnoortheen commented on xonsh/procs/posix.py
> -            origin = BufferedFDParallelReader(origfd, buffer=stdin)
reverted.

2021-05-09 16:52 UTC, daniel-shimon approved these changes
Great!

2021-05-09 20:11 UTC, daniel-shimon approved these changes

2021-05-10 22:46 UTC, merged