update test xsh use
xonsh/xonsh pull request #4581
Opened 2021-12-02 08:36 UTC by jnoortheen

The test suit depends on the order that the tests run. If the test is ran with `pytest-randomly` it will fail. This refactor is to remove direct modification of XSH singleton and reuse same structure to update XSH as fixtures. 

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

2021-12-10 10:20 UTC, agoose77 commented
This is a really important PR, nice work @jnoortheen! It will be good to make the number of places that we refer to `XSH` smaller.

2021-12-10 10:28 UTC, jnoortheen commented
> This is a really important PR, nice work @jnoortheen! It will be good to make the number of places that we refer to `XSH` smaller.

Yes sure. Are you still working on https://github.com/xonsh/xonsh/pull/4540 ? it seems nice. Could you fix the failing tests?

2021-12-10 11:18 UTC, agoose77 commented
> > This is a really important PR, nice work @jnoortheen! It will be good to make the number of places that we refer to `XSH` smaller.
> 
> Yes sure. Are you still working on #4540 ? it seems nice. Could you fix the failing tests?

I am not working on it right now - I'm finishing my PhD, so I don't have a huge amount of time for other projects just at the moment. I will try and get to it, but if you feel like looking at it and fixing the tests, you're more than welcome!

2021-12-12 16:28 UTC, jnoortheen commented
@gforsyth could you review this? It tries to streamline the ways in which the tests access XonshSession object. 

Not including news item, since this is concerned with xonsh developers mostly.

2021-12-13 16:08 UTC, gforsyth requested changes
Thanks for putting this together @jnoortheen.  Definitely on board for the tests being robust and non-leaky.  I'll try to look at the rest of this later.

There seem to be a bunch of additional changes here, including adding an undocumented keyword to the `execer` and changing a bunch of variable names.  Those should be handled in separate PRs, the context-switching overhead for the reviewer is non-trivial.

2021-12-14 04:01 UTC, jnoortheen commented on tests/completers/test_command_completers.py
> +    pass
This is an auto-use fixture. It is needed by other tests in the module.

2021-12-14 04:07 UTC, jnoortheen commented on tests/completers/test_pip_completer.py
> +
This is the fast way to update the attribute. `.update` will call the register on every variable and may result in subprocess calls for LSCOLORS, which is already done for this os_env

2021-12-14 04:11 UTC, jnoortheen commented on tests/conftest.py
> +        return xession.commands_cache
This is more straight forward than changing the private attributes of `xession.commands_cache` (atleast for this test). Do you have any suggestions?

2021-12-23 08:29 UTC, jnoortheen commented on tests/completers/test_pip_completer.py
> +
Also the change that we do is when the attribute is set directly. monkeypatch is acceptable since it will be undone when the test ends

2022-01-05 14:49 UTC, gforsyth commented on tests/conftest.py
> +        return xession.commands_cache
sorry, I missed the `commands_cache` import above.

2022-01-05 15:05 UTC, jnoortheen commented on tests/completers/test_pip_completer.py
> +
I checked the timing, there is not much difference using the update. I have addd this change.

2022-01-05 15:11 UTC, jnoortheen commented on tests/completers/test_pip_completer.py
> +
the change makes those tests fail. https://github.com/xonsh/xonsh/runs/4716286936?check_suite_focus=true

I am reverting.

2022-01-07 22:15 UTC, jnoortheen commented
@gforsyth can we speed this up please? I had to fix the conflicts each time.

2022-01-07 22:33 UTC, gforsyth approved these changes
sorry for the delay @jnoortheen

2022-01-07 22:33 UTC, merged