Ref4 gitstatus modular
xonsh/xonsh pull request #4697
Opened 2022-03-06 17:08 UTC by jnoortheen

This is created after needing to reuse and extend gitstatus from prompt function in efficient way. 
Possibly we can close #1831 #1756 #4493 after this

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

2022-03-14 19:47 UTC, jnoortheen commented on xonsh/prompt/base.py
> +class BasePromptFld:
I am not opposed to that. I prefer shorter names when they are expressive enough.

2022-03-15 14:22 UTC, gforsyth requested changes
Hey @jnoortheen -- thanks for putting this together, it seems like a big improvement!
I've called out a few nits in the code -- I also have two asks for this:
1. Can we make the `repr` of `PROMPT_FIELDS` a little friendlier?  Maybe `list($PROMPT_FIELDS.items())`  or similar?
2. Some docs on how to customize the prompt, especially bits of `gitstatus`

2022-03-17 13:34 UTC, jnoortheen commented on xonsh/prompt/base.py
> +        #     self._matcher.get_module(item)
done

2022-03-17 13:34 UTC, jnoortheen commented on xonsh/prompt/base.py
> +class BasePromptFld:
done

2022-03-19 19:29 UTC, jnoortheen commented
@gforsyth I have added docs to the gitstatus module

2022-03-21 15:18 UTC, merged